### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by leongaban** [dakk/lisk-cmd#2]
Would be nice if you could do `lisk-cmd balance alias` to find balance by alias

<img width="345" alt="screen shot 2017-06-18 at 8 40 39 am" src="https://user-images.githubusercontent.com/191636/27261108-f427d020-5401-11e7-9c86-1da98712f465.png">

**Comment by dakk** [comment]
good idea, I'll implement it

**Comment by dakk** [comment]
Implemented: https://github.com/dakk/lisk-cmd/commit/ddafa4cac6d53e1e188b6cebbe6d3bc7ee8525bc
Released on npm with version number: 0.4.6
